// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "GravityExplorer",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "GravityExplorer",
            targets: ["GravityExplorer"],
            bundleIdentifier: "com.gravity.explorer",
            teamIdentifier: "JTP35H7YAK",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .rocket),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "GravityExplorer",
            path: "GravityExplorer",
            resources: [
                .process("../Resources/Assets.xcassets")
            ]
        )
    ]
)